Repository intel/intel-xpu-backend-for-triton, pull requests merged in 2024-02, with the labels that each got.

#431 Enable some tests and xfail test that also fails for NVIDIA
  python/test/regression/test_cast_matmul.py
  python/test/unit/language/test_block_pointer.py
  python/test/unit/language/test_core.py
  python/test/unit/operators/test_matmul.py
Labels: tests

#463 Enable more test_matmul.py scenarios
  python/test/unit/operators/test_matmul.py
  scripts/compile-triton.sh
Labels: tests

#462 Add build instructions
  docs/build.md
Labels: documentation

#479 Synchronize before computing end times
  python/triton/testing.py
Labels: tests: ut, performance, tests: tutorials

#481 Port test_fp8_dot_acc to XPU and adjust problem size
  python/test/unit/language/test_core.py
Labels: tests: ut
