Repository intel/intel-xpu-backend-for-triton, pull requests merged in 2024-01, with the labels that each got.

#177 Update `test_core_xpu.py`
  python/test/unit/language/test_core_xpu.py
Labels: LLVM Codegen

#183 Merge OpenAI Triton commit `72c9833`
  .github/workflows/integration-tests.yml
  python/setup.py
  python/src/triton.cc
  python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
  python/test/unit/language/test_core_xpu.py
  python/test/unit/runtime/test_subproc.py
  python/test/unit/tools/test_aot.py
  python/triton/__init__.py
  python/triton/compiler/__init__.py
  python/triton/compiler/backends/__init__.py
  python/triton/compiler/backends/cuda.py
  python/triton/compiler/backends/xpu.py
  python/triton/compiler/code_generator.py
  python/triton/compiler/compiler.py
  python/triton/compiler/utils.py
  python/triton/language/core.py
  python/triton/language/extra/cuda.py
  python/triton/language/semantic.py
  python/triton/runtime/driver.py
  python/triton/runtime/jit.py
  python/triton/tools/compile.py
Labels: LLVM Codegen

#181 Port core tests for XPU
  .github/workflows/build_and_test.yml
  lib/Target/LLVMIR/LLVMIRTranslation.cpp
  python/test/unit/language/test_core.py
  python/test/unit/language/test_core_xpu.py
  python/triton/common/build.py
  scripts/test-triton.sh
Labels: LLVM Codegen

#184 Fix and enable test_random.py and test_annotations.py
  .github/workflows/build_and_test.yml
  lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
  lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
  python/test/unit/language/test_core.py
  python/triton/language/math.py
  scripts/test-triton.sh
Labels: LLVM Codegen

#179 [FIX] Quick fix issue that call PythonMemAlloc without holding the GIL
  python/src/triton.cc
Labels: LLVM Codegen

#186 Merge OpenAI Triton commit `0e7e7f6`
  docs/python-api/triton.language.rst
  include/triton/Dialect/Triton/IR/TritonOps.td
  lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
  lib/Dialect/TritonGPU/IR/Dialect.cpp
  python/src/triton.cc
  python/test/unit/language/test_core.py
  python/triton/language/core.py
Labels: LLVM Codegen

#193 Merge OpenAI Triton commit `755002b`
  python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
  python/triton/compiler/backends/cuda.py
  python/triton/compiler/backends/xpu.py
  python/triton/compiler/code_generator.py
  python/triton/compiler/compiler.py
  python/triton/runtime/driver.py
  python/triton/runtime/jit.py
  python/triton/tools/compile.py
Labels: LLVM Codegen

#196 Merge OpenAI Triton commit `6efcc92`
  include/triton/Dialect/Triton/IR/TritonOps.td
  include/triton/Dialect/TritonGPU/IR/Traits.h
  include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
  lib/Analysis/Allocation.cpp
  lib/Analysis/Membar.cpp
  lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv1.cpp
  lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
  lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
  lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
  lib/Dialect/Triton/IR/Ops.cpp
  lib/Dialect/TritonGPU/IR/Dialect.cpp
  lib/Dialect/TritonGPU/IR/Traits.cpp
  lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
  lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
  lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
  lib/Dialect/TritonGPU/Transforms/Utility.cpp
  lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
  python/src/triton.cc
  python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
  python/test/unit/language/test_core.py
  python/test/unit/language/test_line_info.py
  python/test/unit/operators/test_matmul.py
  python/triton/compiler/__init__.py
  python/triton/compiler/backends/cuda.py
  python/triton/compiler/compiler.py
  python/triton/language/__init__.py
  python/triton/language/core.py
  python/triton/language/math.py
  python/triton/language/standard.py
  python/triton/ops/__init__.py
  python/triton/ops/matmul.py
  python/triton/runtime/backends/cuda.c
  python/triton/runtime/cache.py
  python/triton/runtime/driver.py
  test/Analysis/test-allocation.mlir
  test/Conversion/tritongpu_to_nvvm.mlir
  test/TritonGPU/combine.mlir
  test/TritonGPU/optimize-locality.mlir
Labels: LLVM Codegen

#187 Fetch the llvm-spirv component automatically if no llvm-spirv specified.
  CMakeLists.txt
  cmake/FindSPIRVToLLVMTranslator.cmake
  lib/Target/SPIRV/CMakeLists.txt
  lib/Target/SPIRV/SPIRVTranslation.cpp
  lib/Target/SPIRV/spirv-llvm-translator.conf
Labels: LLVM Codegen

#189 Update compile-triton.sh to not building `llvm-spirv`
  scripts/compile-triton.sh
Labels: LLVM Codegen

#195 Improve generality of `test-triton.sh`
  scripts/test-triton.sh
Labels: LLVM Codegen

#194 Fix and enable test_block_pointer.py
  .github/workflows/build_and_test.yml
  python/test/unit/language/test_block_pointer.py
  scripts/test-triton.sh
Labels: LLVM Codegen

#203 Merge OpenAI Triton commit `39f4473`
  cmake/llvm-hash.txt
  docs/meetups/12-13-2023/notes.md
  lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
  python/triton/compiler/backends/cuda.py
  python/triton/compiler/code_generator.py
  python/triton/language/math.py
  python/triton/language/semantic.py
  python/triton/language/standard.py
  python/triton/ops/matmul_perf_model.py
  python/triton/runtime/jit.py
  python/triton/testing.py
Labels: LLVM Codegen

#197 [Backend]: Enable libsycl-spirv math function calls
  python/triton/language/math.py
Labels: LLVM Codegen

#227 Port and run runtime tests
  .github/workflows/build_and_test.yml
  .github/workflows/build_and_test_2.yaml
  python/test/unit/runtime/test_autotuner.py
  python/test/unit/runtime/test_cache.py
  python/test/unit/runtime/test_launch.py
  python/test/unit/runtime/test_subproc.py
  scripts/test-triton.sh
Labels: LLVM Codegen

#204 Fix `tt.dot` codegen when input operands are integers
  lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMA.cpp
  lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
  lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
  python/test/unit/language/test_line_info.py
Labels: LLVM Codegen

#292 Fix `tl.device_print` code generation for XPU
  lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
  lib/Conversion/TritonGPUToLLVM/Utility.cpp
  scripts/test-triton.sh
Labels: bug, LLVM Codegen

#306 [UT]: Fix `test_propagate_nan`
  lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
  python/test/unit/language/test_core.py
Labels: bug, LLVM Codegen

#303 Enable `test_subprocess.py` and fix codegen for `tl.print`
  .github/workflows/build_and_test.yml
  lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
  python/test/unit/language/test_subprocess.py
  scripts/test-triton.sh
Labels: LLVM Codegen

#325 Fix `test_op` in test_cross_entropy.py
  python/test/unit/operators/test_cross_entropy.py
Labels: LLVM Codegen, tests

#347 Enable `test_max_num_imprecise_acc` for xpu
  python/test/unit/language/test_core.py
Labels: tests

#346 Update build_from_source.md
  docs/build_from_source.md
Labels: SPIRV

#359 Reduce workload size temporarily for tutorial `03-matrix-multiplication.py`
  .github/workflows/build_and_test.yml
  python/tutorials/03-matrix-multiplication.py
  scripts/test-triton.sh
Labels: tests

#234 [BACKEND] Added sycl backend support
  python/triton/compiler/compiler.py
  python/triton/runtime/jit.py
  third_party/intel/backend/driver.c
  third_party/intel/backend/driver.py
Labels: enhancement

#360 Reduce workload size temporarily for tutorial `08-experimental-block-pointers.py`
  .github/workflows/build_and_test.yml
  python/tutorials/08-experimental-block-pointer.py
  scripts/test-triton.sh
Labels: tests

#318 [WORKAROUND]: Fix UCmp op not support i1 type
  lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
Labels: e2e, SPIRV
