Repository intel/intel-xpu-backend-for-triton, pull requests merged in 2024-12, with the labels that each got.

#2893 [XPU][TritonGEN] Replace subgroup reduce and scan
  test/Conversion/intel/tritongpu_to_gen.mlir
  test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
  test/TritonGEN/gpu-to-tritongen.mlir
  test/TritonGEN/tritongen-invalid.mlir
  test/TritonGEN/tritongen-to-llvm.mlir
  test/TritonGEN/tritongen.mlir
  test/TritonIntelGPU/tritongpu_reduce_op_lowering.mlir
  third_party/intel/include/Dialect/TritonGEN/IR/TritonGENOps.td
  third_party/intel/lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
  third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
  third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
  third_party/intel/lib/TritonIntelGPUToLLVM/SPIRVSubgroupOps.h
  third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
  third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
Labels: code quality

#2998 [Release Only Changes] Remove git commit hash in wheel name
  python/setup.py
Labels: upstream: pytorch

#2916 [CommonCodeClean] Remove `getElemsPerThreadForOperands`
  include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
  lib/Dialect/TritonGPU/IR/Dialect.cpp
  lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
  third_party/intel/include/Dialect/TritonIntelGPU/IR/TritonIntelGPUAttrDefs.td
  third_party/intel/lib/Dialect/TritonIntelGPU/IR/Dialect.cpp
Labels: upstream: triton
