Repository intel/intel-xpu-backend-for-triton, pull requests merged in 2024-04, with the labels that each got.

#788 Decode `version` bytes to str in hash function
  third_party/intel/backend/compiler.py
Labels: bug

#777 Limit the atomic_rmw lowering vec length to out_elem_bits / in_elem_bits
  third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp
Labels: bug, tests: e2e

#776 [BACKEND][TRANSFORM] add a pass to decompose tritongpu to match target size
  include/triton/Dialect/TritonIntelGPU/Transforms/Passes.h
  include/triton/Dialect/TritonIntelGPU/Transforms/Passes.td
  lib/Dialect/TritonIntelGPU/IR/Ops.cpp
  lib/Dialect/TritonIntelGPU/Transforms/CMakeLists.txt
  lib/Dialect/TritonIntelGPU/Transforms/MatchTargetSize.cpp
  test/TritonIntelGPU/match-target-size.mlir
  test/TritonIntelGPU/tritonintelgpu-invalid.mlir
Labels: codegen: gemm, performance
