Repository intel/intel-xpu-backend-for-triton, pull requests merged in 2024-11, with the labels that each got.

#2632 [NIT][OptRed] Cleanup `-tritonintelgpu-optimize-reduction-locality` code
  third_party/intel/lib/TritonIntelGPUTransforms/OptimizeReductionLocality.cpp
Labels: code quality

#2638 [XPU][Alloc] Optimize SLM allocation size for sub-group layout conversions
  test/Conversion/intel/intel-allocate-shared-memory.mlir
  test/Conversion/intel/sub-group-shuffle.mlir
  third_party/intel/lib/Analysis/Allocation.cpp
Labels: performance, codegen: attention

#2640 [XPU][Membar] Define basic Intel-specific `Membar` filter
  test/Conversion/intel/sub-group-transpose.mlir
  third_party/intel/include/Analysis/Membar.h
  third_party/intel/lib/Analysis/CMakeLists.txt
  third_party/intel/lib/Analysis/Membar.cpp
  third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp
Labels: performance, codegen: attention

#2631 [XPU][OptEW] Define `-intel-triton-optimize-elementwise-parallelism` pass
  test/TritonIntelGPU/optimize-elementwise.mlir
  third_party/intel/include/Dialect/TritonIntelGPU/Transforms/Passes.td
  third_party/intel/lib/TritonIntelGPUTransforms/CMakeLists.txt
  third_party/intel/lib/TritonIntelGPUTransforms/OptimizeElementwiseParallelism.cpp
Labels: performance, codegen: attention

#2670 [XPU][OptEW] Allow multiple warps in non-sliced dimension
  test/TritonIntelGPU/optimize-elementwise.mlir
  third_party/intel/lib/TritonIntelGPUTransforms/OptimizeElementwiseParallelism.cpp
Labels: performance, codegen: attention

#2681 Revert "Revert "[frontend] Remove Complex Regex for MLIR Parsing (#4924)""
  python/src/ir.cc
  python/test/unit/tools/test_irsource.py
  python/triton/compiler/__init__.py
  python/triton/compiler/compiler.py
Labels: upstream: triton

#2769 [XPU][TritonGPUToLLVM] Avoid bank conflicts in sub-group transposes
  test/Conversion/intel/intel-allocate-shared-memory.mlir
  test/Conversion/intel/sub-group-transpose.mlir
  third_party/intel/lib/Analysis/Allocation.cpp
  third_party/intel/lib/TritonIntelGPUToLLVM/ConvertLayoutOpToLLVM.cpp
Labels: performance, codegen: attention

#2802 [XPU][TritonGEN] Drop `RoundingModeAttr`
  third_party/intel/include/Dialect/TritonGEN/IR/TritonGENAttrDefs.td
Labels: code quality

#2814 [XPU][TritonGEN] Replace split barrier ops usages with SPIR-V ops
  test/TritonGEN/tritongen-to-llvm.mlir
  test/TritonGEN/tritongen.mlir
  test/TritonIntelGPU/prefetch-block.mlir
  third_party/intel/include/Dialect/TritonGEN/IR/TritonGENOps.td
  third_party/intel/include/Dialect/TritonIntelGPU/Transforms/Passes.td
  third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
  third_party/intel/lib/TritonIntelGPUTransforms/CMakeLists.txt
  third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
Labels: code quality

#2786 [XPU][TritonIntelGPUToLLVM] Add support for more transpose kinds
  test/Conversion/intel/intel-allocate-shared-memory.mlir
  test/Conversion/intel/sub-group-transpose.mlir
  third_party/intel/lib/Analysis/Utility.cpp
  third_party/intel/lib/TritonIntelGPUToLLVM/ConvertLayoutOpToLLVM.cpp
Labels: codegen: attention
